#!/usr/bin/env python3
"""
Pre-Publication Verification & Fact-Checking Gate
=================================================
Ensures every post generated by AI meets strict factual, structural,
and financial compliance standards before reaching any public platform (eToro, Telegram, etc.).

Pipeline:
  1. Deterministic Fast-Gate:
     • Validates asset distribution policy (blocks dividend/yield claims on accumulating assets)
     • Validates eToro format (strips markdown bold `**`, validates cashtags)
     • Ignores currency/numerical amounts like $10.000 or $500
     • Verifies character limits
  2. AI Adversarial Reviewer ("LLM-as-a-Judge" / Self-Correction Critic):
     • Audits drafted post against Single Source of Truth (`PORTFOLIO_ASSETS_METADATA`)
     • Detects hallucinations, sector distortions, or incorrect business models
     • Auto-corrects text or issues a hard REJECT if unrecoverable
"""

import os
import re
import json
import time
from typing import Tuple, List, Dict, Optional, Any

try:
    from google import genai
    from google.genai import types
    GENAI_AVAILABLE = True
except ImportError:
    GENAI_AVAILABLE = False

try:
    from portfolio_manager import PORTFOLIO_ASSETS_METADATA, get_asset_metadata
except ImportError:
    from src.portfolio_manager import PORTFOLIO_ASSETS_METADATA, get_asset_metadata

# Models for the adversarial reviewer (high reasoning, low hallucination)
REVIEWER_MODELS = [
    'gemini-3.7-flash',
    'gemini-3.6-flash',
    'gemini-3.5-flash',
    'gemini-2.5-flash',
]
try:
    from ai_model_cascade import REVIEWER_GEMINI_MODELS, DEFAULT_GEMINI_MODELS
    REVIEWER_MODELS = list(REVIEWER_GEMINI_MODELS)
except ImportError:
    try:
        from src.ai_model_cascade import REVIEWER_GEMINI_MODELS, DEFAULT_GEMINI_MODELS
        REVIEWER_MODELS = list(REVIEWER_GEMINI_MODELS)
    except ImportError:
        REVIEWER_MODELS = [
            'gemini-3.1-pro',
            'gemini-3.8-flash',
            'gemini-3.7-flash',
            'gemini-3.6-flash',
            'gemini-3.5-flash',
            'gemini-2.5-flash',
        ]


# Claims that assert a positive dividend/yield payout
POSITIVE_DIVIDEND_CLAIMS = [
    r'(ottimo|alto|generoso|ricco|stabile|crescente|interessante)\s+dividendo',
    r'dividendo\s+(del|pari a|annuale|semestrale|trimestrale|mensile)',
    r'yield\s+(del|da dividendo)',
    r'rendimento\s+da\s+dividendo',
    r'dividend\s+yield',
    r'cedola\s+(del|semestrale|trimestrale|annuale|periodica)',
    r'paga\s+(un\s+)?dividendo',
    r'distribuisce\s+(un\s+)?(dividendo|cedola|rendimento)',
    r'flusso\s+(di cassa passivo|cedolare)',
    r'societ[àa]\s+ad\s+alto\s+dividendo',
    r'titoli\s+ad\s+alto\s+dividendo',
    r'investimento\s+da\s+reddito',
    r'base\s+di\s+reddito',
]

# Negations explaining that the asset does NOT distribute dividends
DIVIDEND_NEGATIONS = [
    r'nessun\s+dividendo',
    r'senza\s+dividendo',
    r'senza\s+cedol',
    r'non\s+distribuisce\s+(un\s+)?(dividendo|cedol)',
    r'non\s+stacca\s+(un\s+)?(dividendo|cedol)',
    r'zero\s+dividendi',
    r'zero\s+cedole',
    r'nessuna\s+cedola',
    r'non\s+paga\s+(un\s+)?dividendo',
    r'non\s+offre\s+(un\s+)?dividendo',
    r'ad\s+accumulazione\s+senza\s+dividendi',
]


def clean_etoro_formatting(text: str) -> str:
    """
    Remove formatting elements that break on eToro or look messy:
    - Markdown asterisks `**bold**`, `*italic*`, `__bold__`
    - Parentheses wrapping cashtags e.g. '($NVDA)' -> ' $NVDA '
    """
    if not text:
        return ""

    # Remove bold/italic markdown asterisks & underscores
    cleaned = re.sub(r'\*\*(.*?)\*\*', r'\1', text, flags=re.DOTALL)
    cleaned = re.sub(r'__(.*?)__', r'\1', cleaned, flags=re.DOTALL)
    cleaned = re.sub(r'(?<!\w)\*([^\*\n]+)\*(?!\w)', r'\1', cleaned)
    cleaned = cleaned.replace('**', '').replace('__', '')

    # Fix parenthesized cashtags: '($TICKER)' -> ' $TICKER '
    cleaned = re.sub(r'\(\$([A-Za-z0-9\.\-]+)\)', r' $\1 ', cleaned)

    # Clean multiple spaces caused by regex replacements
    cleaned = re.sub(r' +', ' ', cleaned)
    return cleaned.strip()


def extract_cashtags(text: str) -> List[str]:
    """
    Extract unique $TICKER cashtags from text in uppercase.
    Ignores currency amounts like $10.000, $10,000, $500.
    """
    if not text:
        return []
    raw_tags = re.findall(r'\$([A-Za-z0-9\.\-]+)', text)
    seen = set()
    unique_tags = []
    for t in raw_tags:
        # Ignore pure numerical / currency values (e.g. 10.000, 500, 10,000)
        if re.match(r'^\d+(?:[.,]\d+)*$', t):
            continue
        t_clean = t.upper()
        if t_clean not in seen:
            seen.add(t_clean)
            unique_tags.append(t_clean)
    return unique_tags


def verify_post_deterministic(text: str, primary_ticker: Optional[str] = None) -> Tuple[bool, List[str], str]:
    """
    Fast, rule-based verification against PORTFOLIO_ASSETS_METADATA.
    
    Returns:
        tuple: (is_clean, issues_list, cleaned_text)
    """
    issues = []
    cleaned_text = clean_etoro_formatting(text)

    if not cleaned_text:
        return False, ["Il testo del post è vuoto."], ""

    # Collect tickers to verify
    tickers_to_check = extract_cashtags(cleaned_text)
    primary_clean = primary_ticker.upper() if primary_ticker else None

    # Check length
    if len(cleaned_text) > 3900:
        issues.append(f"WARNING: Il post eccede la lunghezza raccomandata eToro ({len(cleaned_text)} > 3900 car).")

    text_lower = cleaned_text.lower()
    has_positive_div_claim = any(re.search(p, text_lower) for p in POSITIVE_DIVIDEND_CLAIMS)
    has_plain_div_word = bool(re.search(r'\b(dividendo|dividendi|cedola|cedole)\b', text_lower))
    has_negation = any(re.search(n, text_lower) for n in DIVIDEND_NEGATIONS)

    # Check for purged assets that must never appear in active communications
    for tag in tickers_to_check:
        if tag in ("XEON.DE", "XEON"):
            issues.append(
                f"CRITICAL: L'asset ${tag} è stato definitivamente dismesso dal portafoglio e non deve comparire in alcun post o commento."
            )

    # 1. Primary Ticker Check (if post focuses on a specific asset)
    if primary_clean and primary_clean in PORTFOLIO_ASSETS_METADATA:
        meta = PORTFOLIO_ASSETS_METADATA[primary_clean]
        is_div_paying = meta.get("is_dividend_paying", False)
        if not is_div_paying:
            if has_positive_div_claim:
                issues.append(
                    f"CRITICAL: L'asset primario ${primary_clean} ({meta.get('name')}) è ad ACCUMULAZIONE / NON DIVIDENDO, "
                    f"ma il post afferma la presenza di dividendi/cedole/yield."
                )
            elif has_plain_div_word and not has_negation:
                issues.append(
                    f"CRITICAL: L'asset primario ${primary_clean} ({meta.get('name')}) è ad ACCUMULAZIONE / NON DIVIDENDO, "
                    f"ma il post cita dividendi senza negazione esplicita (es. 'nessun dividendo')."
                )

    # 2. General Multi-Ticker Check (only if no dividend-paying primary ticker is the subject)
    # If primary ticker is a certified dividend payer, general dividend words are expected.
    primary_is_payer = False
    if primary_clean and primary_clean in PORTFOLIO_ASSETS_METADATA:
        primary_is_payer = PORTFOLIO_ASSETS_METADATA[primary_clean].get("is_dividend_paying", False)

    if not primary_is_payer:
        # Check if non-dividend assets are falsely attributed dividends in their paragraph
        paragraphs = cleaned_text.split("\n\n")
        for para in paragraphs:
            para_lower = para.lower()
            para_has_positive = any(re.search(p, para_lower) for p in POSITIVE_DIVIDEND_CLAIMS)
            para_has_div_word = bool(re.search(r'\b(dividendo|dividendi|cedola|cedole)\b', para_lower))
            para_has_neg = any(re.search(n, para_lower) for n in DIVIDEND_NEGATIONS)

            para_tags = extract_cashtags(para)
            for t in para_tags:
                if t in PORTFOLIO_ASSETS_METADATA:
                    meta = PORTFOLIO_ASSETS_METADATA[t]
                    if not meta.get("is_dividend_paying", False):
                        if para_has_positive or (para_has_div_word and not para_has_neg):
                            issues.append(
                                f"CRITICAL: L'asset ${t} ({meta.get('name')}) è ad ACCUMULAZIONE / NON DIVIDENDO, "
                                f"ma è associato a termini di dividendo nel testo."
                            )
                            break

    is_clean = len([i for i in issues if i.startswith("CRITICAL")]) == 0
    return is_clean, issues, cleaned_text


def audit_post_with_ai_reviewer(
    text: str,
    primary_ticker: Optional[str] = None,
    session_name: Optional[str] = None,
    generator_model: Optional[str] = None,
) -> Dict[str, Any]:
    """
    Invokes an adversarial AI reviewer (or self-critic) to audit the post.
    Uses temperature 0.1 and strict JSON output schema.
    """
    if not GENAI_AVAILABLE:
        return {
            "decision": "APPROVE",
            "score": 100,
            "issues": [],
            "verified_text": text,
            "explanation": "google-genai non disponibile, AI review saltata."
        }

    api_key = os.environ.get("GEMINI_API_KEY")
    if not api_key:
        return {
            "decision": "APPROVE",
            "score": 100,
            "issues": [],
            "verified_text": text,
            "explanation": "GEMINI_API_KEY non configurata, AI review saltata."
        }

    # Extract all relevant metadata for tickers mentioned
    tickers = extract_cashtags(text)
    if primary_ticker and primary_ticker.upper() not in tickers:
        tickers.append(primary_ticker.upper())

    metadata_context_lines = []
    for t in tickers:
        if t in PORTFOLIO_ASSETS_METADATA:
            meta = PORTFOLIO_ASSETS_METADATA[t]
            metadata_context_lines.append(
                f"• ${t}:\n"
                f"  - Nome Ufficiale: {meta.get('name')}\n"
                f"  - Asset Class: {meta.get('asset_class')}\n"
                f"  - Settore: {meta.get('sector')}\n"
                f"  - Paga Dividendi: {'SÌ' if meta.get('is_dividend_paying') else 'NO (ACCUMULAZIONE / ZERO CEDOLE DISTRIBUITE)'}\n"
                f"  - Politica Dividendi: {meta.get('dividend_policy')}\n"
                f"  - Tesi Fondamentale: {meta.get('thesis')}\n"
                f"  - Catalizzatori: {', '.join(meta.get('upside_catalysts', []))}\n"
                f"  - Rischi: {', '.join(meta.get('downside_risks', []))}"
            )

    metadata_context = "\n\n".join(metadata_context_lines) if metadata_context_lines else "Nessun asset specifico di portafoglio identificato."

    # Pick reviewer model (prefer an alternative model if generator_model is specified)
    reviewer_model = REVIEWER_MODELS[0]
    if generator_model and len(REVIEWER_MODELS) > 1:
        # Pick the second model in priority if available to ensure true dual-model check
        for m in REVIEWER_MODELS:
            if m != generator_model:
                reviewer_model = m
                break

    audit_prompt = f"""Sei il Lead Financial Fact-Checker & Compliance Auditor per un portfolio pubblico su eToro.
Il tuo compito è analizzare con estremo rigore critico il seguente POST generato per i social/eToro e verificare che NON contenga alcuna allucinazione o inesattezza finanziaria rispetto alla SINGLE SOURCE OF TRUTH dei dati ufficiali.

=========================
METADATI UFFICIALI DEGLI ASSET COINVOLTI (SINGLE SOURCE OF TRUTH):
=========================
{metadata_context}

=========================
TESTO DEL POST DA REVISIONARE:
=========================
{text}

=========================
REGOLE DI VERIFICA TASSATIVE:
=========================
1. VERIFICA DIVIDENDI (CRITICA): Se un asset ha 'Paga Dividendi: NO (ACCUMULAZIONE / ZERO CEDOLE DISTRIBUITE)' (come ad esempio $WDEF.L, $INDO.PA, $IB01.L, $XEON.DE, $PPFB.DE), il post NON DEVE IN ALCUN MODO attribuirgli dividendi, cedole, rendimenti da dividendo o considerarlo un asset di "income/reddito da dividendo". Se questa allucinazione è presente, DEVI CORREGGERLA spiegando che l'asset capitalizza tutti i proventi nel NAV ad accumulazione, oppure rimuovere ogni riferimento ai dividendi.
1. VERIFICA DIVIDENDI (CRITICA): Se un asset ha 'Paga Dividendi: NO (ACCUMULAZIONE / ZERO CEDOLE DISTRIBUITE)' (come ad esempio $WDEF.L, $INDO.PA, $IB01.L, $PPFB.DE), il post NON DEVE IN ALCUN MODO attribuirgli dividendi, cedole, rendimenti da dividendo o considerarlo un asset di "income/reddito da dividendo". Se questa allucinazione è presente, DEVI CORREGGERLA spiegando che l'asset capitalizza tutti i proventi nel NAV ad accumulazione, oppure rimuovere ogni riferimento ai dividendi.
2. VERIFICA IDENTITÀ & SETTORE: Il nome dell'azienda o dell'ETF e il settore devono corrispondere esattamente ai dati ufficiali. (Es: $WDEF.L è WisdomTree Europe Defence UCITS ETF, settore Difesa e Aerospazio europeo, NON Equity Income).
3. FORMATTAZIONE ETORO: Rimuovi qualsiasi markdown bold '**' o '__' perché eToro non lo supporta. I cashtag devono avere lo spazio prima e dopo (es. ' $NVDA ').
4. DECISIONE:
   - Se il post è perfetto e veritiero -> decision: "APPROVE", verified_text: il testo originale pulito.
   - Se il post contiene inesattezze o allucinazioni ma è correggibile preservando struttura e stile -> decision: "AUTO_CORRECT", verified_text: il testo integralmente corretto e bonificato.
   - Se il post è totalmente fuorviante, incoerente o dannoso -> decision: "REJECT", verified_text: "".

Restituisci SOLO un oggetto JSON valido con il seguente schema:
{{
  "decision": "APPROVE" | "AUTO_CORRECT" | "REJECT",
  "score": 100,
  "hallucinations_detected": ["lista di eventuali allucinazioni trovate"],
  "rule_violations": ["lista di eventuali violazioni di regole"],
  "verified_text": "Testo finale verificato e pronto per la pubblicazione",
  "explanation": "Breve sintesi dell'audit (in italiano)"
}}
"""

    client = genai.Client(api_key=api_key)

    for model_name in [reviewer_model] + [m for m in REVIEWER_MODELS if m != reviewer_model]:
        try:
            print(f"   🔍 AI Fact-Checker Reviewer running on model: {model_name}...")
            config = types.GenerateContentConfig(
                temperature=0.1,
                response_mime_type="application/json"
            )
            response = client.models.generate_content(
                model=model_name,
                contents=audit_prompt,
                config=config
            )

            if response and response.text:
                raw_text = response.text.strip()
                # Clean possible markdown wrapping if any
                raw_text = re.sub(r'^```(?:json)?\s*', '', raw_text)
                raw_text = re.sub(r'\s*```$', '', raw_text)
                data = json.loads(raw_text)
                if "decision" in data and "verified_text" in data:
                    print(f"   ✅ AI Reviewer complete ({model_name}) — Decision: {data.get('decision')} (Score: {data.get('score', 'N/A')}/100)")
                    return data
        except Exception as err:
            print(f"   ⚠️ Reviewer model {model_name} attempt failed: {err}")
            time.sleep(1.0)
            continue

    # Fallback if AI reviewer calls fail
    return {
        "decision": "APPROVE",
        "score": 85,
        "issues": ["AI Reviewer non disponibile, applicate solo regole deterministiche."],
        "verified_text": clean_etoro_formatting(text),
        "explanation": "Fallback deterministico attivo."
    }


def verify_and_clean_post(
    text: str,
    primary_ticker: Optional[str] = None,
    session_name: Optional[str] = None,
    generator_model: Optional[str] = None,
    run_ai_review: bool = True,
) -> Tuple[bool, str, Dict[str, Any]]:
    """
    Complete pre-publication verification pipeline.
    Combines Fast-Gate deterministic validation with Adversarial AI Review.

    Returns:
        tuple: (is_approved: bool, final_published_text: str, audit_summary: dict)
    """
    print(f"\n🛡️ PRE-PUBLICATION VERIFICATION GATE:")
    print(f"   Primary Ticker: {primary_ticker or 'N/A'} | Session: {session_name or 'General'}")

    # Stage 1: Deterministic check
    is_clean, issues, cleaned_text = verify_post_deterministic(text, primary_ticker=primary_ticker)

    if issues:
        print(f"   ⚠️ Deterministic Fast-Gate issues detected:")
        for issue in issues:
            print(f"      - {issue}")
    else:
        print(f"   ✓ Deterministic Fast-Gate: PASSED (clean formatting & rules)")

    # If critical issues found or AI review requested, run Stage 2
    audit_data = {}
    if run_ai_review and GENAI_AVAILABLE and os.environ.get("GEMINI_API_KEY"):
        audit_data = audit_post_with_ai_reviewer(
            text=cleaned_text,
            primary_ticker=primary_ticker,
            session_name=session_name,
            generator_model=generator_model,
        )

        decision = audit_data.get("decision", "APPROVE")
        verified_text = audit_data.get("verified_text", cleaned_text)

        if decision == "REJECT":
            print(f"   ❌ POST REJECTED BY AI REVIEWER: {audit_data.get('explanation')}")
            return False, "", audit_data

        if decision == "AUTO_CORRECT":
            print(f"   🛠️ POST AUTO-CORRECTED BY AI REVIEWER:")
            print(f"      Explanation: {audit_data.get('explanation')}")
            for h in audit_data.get("hallucinations_detected", []):
                print(f"      • Fixed hallucination: {h}")
            final_text = clean_etoro_formatting(verified_text)
            return True, final_text, audit_data

        # APPROVE
        print(f"   ✅ POST APPROVED BY AI REVIEWER.")
        return True, clean_etoro_formatting(verified_text), audit_data

    # If AI review not available or skipped, use deterministic outcome
    if not is_clean:
        # Check if there are critical errors that cannot be published without AI auto-correct
        critical_issues = [i for i in issues if i.startswith("CRITICAL")]
        if critical_issues:
            print(f"   ❌ POST BLOCKED by Deterministic Gate (Critical rule violation without AI corrector): {critical_issues[0]}")
            return False, "", {"decision": "REJECT", "issues": issues}

    return True, cleaned_text, {"decision": "APPROVE", "issues": issues}


def audit_comment_with_ai_reviewer(
    text: str,
    user_comment: Optional[str] = None,
    user_author: Optional[str] = None,
    primary_ticker: Optional[str] = None,
    generator_model: Optional[str] = None,
) -> Dict[str, Any]:
    """
    Invokes an adversarial AI reviewer to audit a community reply or catalyst comment.
    Checks against Single Source of Truth (PORTFOLIO_ASSETS_METADATA), ensuring:
      1. Zero financial hallucinations (no dividends for accumulating ETFs, no fake tickers).
      2. Perfect compliance (Risk 3/10, 0 leverage, no financial advice).
      3. Substance and relevance to user query.
      4. Syntax compliance (no markdown **, complete sentence ending).
    """
    if not GENAI_AVAILABLE:
        return {
            "decision": "APPROVE",
            "score": 100,
            "issues": [],
            "verified_text": clean_etoro_formatting(text),
            "explanation": "google-genai non disponibile, AI review commento saltata."
        }

    api_key = os.environ.get("GEMINI_API_KEY")
    if not api_key:
        return {
            "decision": "APPROVE",
            "score": 100,
            "issues": [],
            "verified_text": clean_etoro_formatting(text),
            "explanation": "GEMINI_API_KEY non configurata, AI review commento saltata."
        }

    tickers = extract_cashtags(text)
    if user_comment:
        tickers.extend(extract_cashtags(user_comment))
    if primary_ticker and primary_ticker.upper() not in tickers:
        tickers.append(primary_ticker.upper())

    metadata_lines = []
    for t in set(tickers):
        if t in PORTFOLIO_ASSETS_METADATA:
            meta = PORTFOLIO_ASSETS_METADATA[t]
            metadata_lines.append(
                f"• ${t} ({meta.get('name')}):\n"
                f"  - Settore: {meta.get('sector')}\n"
                f"  - Dividendi: {'SÌ' if meta.get('is_dividend_paying') else 'NO (ACCUMULAZIONE / ZERO CEDOLE DISTRIBUITE)'}\n"
                f"  - Politica: {meta.get('dividend_policy')}\n"
                f"  - Tesi: {meta.get('thesis')}"
            )

    meta_context = "\n\n".join(metadata_lines) if metadata_lines else "Nessun asset specifico di portafoglio coinvolto."

    reviewer_model = REVIEWER_MODELS[0]
    if generator_model and len(REVIEWER_MODELS) > 1:
        for m in REVIEWER_MODELS:
            if m != generator_model:
                reviewer_model = m
                break

    if user_comment:
        user_context_info = f'Utente: @{user_author}\nCommento: "{user_comment}"'
    else:
        user_context_info = 'N/A (Commento autonomo su catalyst o notizia)'

    prompt = f"""Sei il Lead Compliance and Fact-Checking Auditor per il canale eToro di Andrea Ravalli (+200%, Risk 3/10, multi-asset, zero leva).
Verifica con la massima severità la seguente RISPOSTA / COMMENTO per la community prima della pubblicazione:

CONTESTO UTENTE / DOMANDA ORIGINALE:
{user_context_info}

METADATI CERTIFICATI PORTAFOGLIO (SINGLE SOURCE OF TRUTH):
{meta_context}

TESTO DA REVISIONARE:
"{text}"

REGOLE DI AUDIT:
1. DIVIETO ASSOLUTO DI CEDOLE SU ASSET AD ACCUMULAZIONE: Se un asset è ad accumulazione ($WDEF.L, $INDO.PA, $IB01.L, $PPFB.DE), non deve mai essere citato come fonte di dividendi o reddito.
2. DIVIETO ASSET DISMESSI: Nessuna menzione di XEON o $XEON.DE (completamente dismesso dal portafoglio).
3. TONO & COMPLIANCE: Rispettoso, pacato, nessun consiglio finanziario sollecitatore ("non è un consiglio finanziario", focus sulla strategia a lungo termine e gestione del rischio 3/10).
4. COMPLETEZZA: Nessuna frase troncata, nessuna interruzione a metà parola o senza punteggiatura/emoji finale. NO markdown con asterischi (**).
5. VERDETTO:
   - "APPROVE": testo eccellente e privo di inesattezze.
   - "AUTO_CORRECT": se ci sono lievi inesattezze o refusi ma è correggibile, fornisci in verified_text la versione corretta completa e pronta per eToro.
   - "REJECT": se inaccettabile o fuorviante.

Restituisci SOLO un JSON valido:
{{
  "decision": "APPROVE" | "AUTO_CORRECT" | "REJECT",
  "score": 100,
  "hallucinations_detected": [],
  "verified_text": "testo bonificato finale",
  "explanation": "breve motivazione in italiano"
}}"""

    client = genai.Client(api_key=api_key)
    for model_name in [reviewer_model] + [m for m in REVIEWER_MODELS if m != reviewer_model]:
        try:
            print(f"   🔍 AI Comment Fact-Checker running on model: {model_name}...")
            config = types.GenerateContentConfig(
                temperature=0.1,
                response_mime_type="application/json"
            )
            response = client.models.generate_content(
                model=model_name,
                contents=prompt,
                config=config
            )
            if response and response.text:
                raw_text = response.text.strip()
                raw_text = re.sub(r'^```(?:json)?\s*', '', raw_text)
                raw_text = re.sub(r'\s*```$', '', raw_text)
                data = json.loads(raw_text)
                if "decision" in data and "verified_text" in data:
                    print(f"   ✅ AI Comment Reviewer complete ({model_name}) — Decision: {data.get('decision')} (Score: {data.get('score', 'N/A')}/100)")
                    return data
        except Exception as err:
            print(f"   ⚠️ Comment Reviewer model {model_name} failed: {err}")
            time.sleep(1.0)
            continue

    return {
        "decision": "APPROVE",
        "score": 85,
        "issues": ["AI Reviewer non disponibile"],
        "verified_text": clean_etoro_formatting(text),
        "explanation": "Fallback deterministico attivo per commento."
    }


def verify_and_clean_comment(
    text: str,
    user_comment: Optional[str] = None,
    user_author: Optional[str] = None,
    primary_ticker: Optional[str] = None,
    generator_model: Optional[str] = None,
    run_ai_review: bool = True,
) -> Tuple[bool, str, Dict[str, Any]]:
    """
    Universal verification pipeline for ANY comment or reply.
    Combines Fast-Gate deterministic validation with Adversarial AI Review.

    Returns:
        (is_approved, clean_text, audit_summary)
    """
    cleaned = clean_etoro_formatting(text)
    if not cleaned:
        return False, "", {"decision": "REJECT", "issues": ["Commento vuoto"]}

    # Fast-gate: check rules
    is_clean, issues, cleaned_text = verify_post_deterministic(cleaned, primary_ticker=primary_ticker)

    # Comments have shorter character limit on eToro (max 1000)
    if len(cleaned_text) > 1000:
        issues.append(f"WARNING: Il commento eccede la lunghezza massima consentita da eToro ({len(cleaned_text)} > 1000).")

    audit_data = {}
    if run_ai_review and GENAI_AVAILABLE and os.environ.get("GEMINI_API_KEY"):
        audit_data = audit_comment_with_ai_reviewer(
            text=cleaned_text,
            user_comment=user_comment,
            user_author=user_author,
            primary_ticker=primary_ticker,
            generator_model=generator_model,
        )
        decision = audit_data.get("decision", "APPROVE")
        verified_text = audit_data.get("verified_text", cleaned_text)

        if decision == "REJECT":
            print(f"   ❌ COMMENT REJECTED BY REVIEWER: {audit_data.get('explanation')}")
            return False, "", audit_data

        if decision == "AUTO_CORRECT":
            print(f"   🛠️ COMMENT AUTO-CORRECTED BY REVIEWER: {audit_data.get('explanation')}")
            final_text = clean_etoro_formatting(verified_text)
            return True, final_text, audit_data

        return True, clean_etoro_formatting(verified_text), audit_data

    # Deterministic fallback
    if not is_clean:
        crit = [i for i in issues if i.startswith("CRITICAL")]
        if crit:
            print(f"   ❌ COMMENT BLOCKED by Deterministic Gate: {crit[0]}")
            return False, "", {"decision": "REJECT", "issues": issues}

    return True, cleaned_text, {"decision": "APPROVE", "issues": issues}


